before_install:
- brew update
- brew upgrade xctool
language: objective-c
script:
- xcodebuild -project SampleiOS.xcodeproj -scheme SampleiOS clean build -sdk iphonesimulator8.1
- xcodebuild -project SampleiOS.xcodeproj -scheme SampleiOS build test -sdk iphonesimulator8.1
